---
# Do not forget to add following ENV vars in GitLab project settings
# GOOGLE_CREDENTIALS, GOOGLE_ACCOUNT, GOOGLE_PROJECT_ID
stages:
 - build
 - tagging
 - apply

variables:
  APP_IMAGE_REGISTRY_URL: eu.gcr.io/${GOOGLE_PROJECT_ID}/myapp
  IMAGE_HASH: ${CI_COMMIT_SHA}

before_script:
 # GCP container registry login magic start
 - echo "$GOOGLE_CREDENTIALS">/etc/key-file.json
 - gcloud auth activate-service-account $GOOGLE_ACCOUNT --key-file /etc/key-file.json
 - gcloud auth configure-docker
 - gcloud container clusters get-credentials cloudweekend --zone europe-west1-d --project $GOOGLE_PROJECT_ID
 # GCP container registry login magic end

build:
  stage: build
  image: adamjanis/cloudweekend-runner
  allow_failure: true
  script:
   - echo ${APP_IMAGE_REGISTRY_URL}:${IMAGE_HASH}
   - docker build -t myapp .
   - docker tag myapp ${APP_IMAGE_REGISTRY_URL}:${IMAGE_HASH}
   - docker push ${APP_IMAGE_REGISTRY_URL}:${IMAGE_HASH}

tag-latest:
  stage: tagging
  image: adamjanis/cloudweekend-runner
  script:
   - docker pull ${APP_IMAGE_REGISTRY_URL}:${IMAGE_HASH}
   - docker tag ${APP_IMAGE_REGISTRY_URL}:${IMAGE_HASH} ${APP_IMAGE_REGISTRY_URL}:latest
   - docker push ${APP_IMAGE_REGISTRY_URL}:latest
  only:
   - master

terraform plan:
  stage: build
  image: adamjanis/cloudweekend-runner
  script:
   - cd terraform
   - terraform init
   - terraform plan

terraform apply:
  stage: apply
  when: manual
  image: adamjanis/cloudweekend-runner
  script:
   - cd terraform
   - terraform init
   - terraform apply -auto-approve
  only:
   - master

apply stable:
  stage: apply
  when: manual
  image: adamjanis/cloudweekend-runner
  environment:
    name: production
    url: http://adam-janis.cloudweekend.kiwi
  script:
    - sed -i -e "s/__IMAGE_HASH__/${CI_COMMIT_SHA}/g" kubernetes/myapp-deployment.yaml
    - kubectl apply -f kubernetes/myapp-deployment.yaml
    - kubectl rollout status -w deployment/myapp
  only:
   - master

apply canary:
  stage: apply
  when: manual
  image: adamjanis/cloudweekend-runner
  environment:
    name: canary
    url: http://adam-janis-canary.cloudweekend.kiwi
  script:
    - sed -i -e "s/__IMAGE_HASH__/${CI_COMMIT_SHA}/g" kubernetes/myapp-canary-deployment.yaml
    - kubectl apply -f kubernetes/myapp-canary-deployment.yaml
    - kubectl rollout status -w deployment/myapp-canary