# https://v1-9.docs.kubernetes.io/docs/concepts/workloads/controllers/deployment/#creating-a-deployment
# https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/tree/master/hello-app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-pod
      track: canary
  template:
    metadata:
      labels:
        app: myapp-pod
        track: canary
    spec:
      containers:
      - name: hello-app
        image: eu.gcr.io/cloudweekend-ab33b7e5/myapp@sha256:2fc02654760f4bfc9e234141931756a0304cba71fc5ee35c631f9898888651e9
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
