apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  - port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app: myapp-pod
  type: NodePort
  sessionAffinity: "ClientIP"
